# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('qtype', models.IntegerField(choices=[(1, '单选'), (2, '多选'), (3, '文本'), (4, '分值')])),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDetial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=32)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=32)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('identify', models.IntegerField(choices=[(1, 'admin'), (2, 'teacher')])),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Classroom')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Questionnaire'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ques_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('user_id', 'ques_id')]),
        ),
    ]
