# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171204_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ques_id',
            new_name='ques',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_id',
            new_name='questionnaire',
        ),
        migrations.RenameField(
            model_name='questiondetial',
            old_name='q_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='class_id',
            new_name='cls',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='class_id',
            new_name='cls',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('user', 'ques')]),
        ),
    ]
