# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171205_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='joinNum',
            field=models.IntegerField(default=0),
        ),
    ]
